services:
  web:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - misioneros_net
    environment:
      DB_HOST: db
      DB_NAME: misioneros_integrales_db
      DB_USER: root
      DB_PASS: secret_password

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: misioneros_integrales_db
      MYSQL_ROOT_PASSWORD: secret_password
    ports:
      - "3308:3306"
    networks:
      - misioneros_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - misioneros_net

networks:
  misioneros_net:
    driver: bridge
